telegram:
  - id: "tel"
    telegram_api_key: "6901900880:AAEmkJD4xkIsPhRkvc_taB9UnJhYGHEZHDk"
    telegram_chat_id: "5268423406"
    telegram_format: "{{data}}"
    telegram_parsemode: "Markdown" # None/Markdown/MarkdownV2/HTML (https://core.telegram.org/bots/api#formatting-options)
